// <auto-generated />
using System;
using ApiWithSwagger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiWithSwagger.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210422103538_Add-Item-and-Deposit")]
    partial class AddItemandDeposit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ApiWithSwagger.Data.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DailyDepositPrice")
                        .HasColumnType("TEXT");

                    b.Property<short>("DepositType")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ItemType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("ApiWithSwagger.Data.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DailyPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.Property<short?>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Received")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Take")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ApiWithSwagger.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("ApiWithSwagger.Data.Item", b =>
                {
                    b.HasOne("ApiWithSwagger.Data.User", null)
                        .WithMany("DepositItems")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ApiWithSwagger.Data.User", b =>
                {
                    b.Navigation("DepositItems");
                });
#pragma warning restore 612, 618
        }
    }
}
